<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>Metropole.Sim</AssemblyName>
    <RootNamespace>Metropole.Sim</RootNamespace>
    <Version>1.6.0</Version>
  </PropertyGroup>
</Project>
