param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\src\Metropole.Game")).Path
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$assetRoot = Join-Path $ProjectRoot "assets\third_party"
$kenneyRoot = Join-Path $assetRoot "kenney"
$audioRoot = Join-Path $assetRoot "audio"
$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("metropole-assets-" + [guid]::NewGuid().ToString("N"))

New-Item -ItemType Directory -Force -Path $kenneyRoot,$audioRoot,$tempRoot | Out-Null

function Download-File([string]$Url, [string]$Path) {
    Write-Host "Downloading $Url"
    Invoke-WebRequest -Uri $Url -OutFile $Path -UseBasicParsing -Headers @{
        "User-Agent" = "Metropole-Asset-Build/1.4"
    }
    if (!(Test-Path $Path) -or (Get-Item $Path).Length -lt 256) {
        throw "Asset download failed or is unexpectedly small: $Url"
    }
}

function Expand-Pack([string]$Url, [string]$Name) {
    $zip = Join-Path $tempRoot "$Name.zip"
    $dir = Join-Path $tempRoot $Name
    Download-File $Url $zip
    Expand-Archive -Path $zip -DestinationPath $dir -Force
    return $dir
}

function Copy-AllModels([string]$PackDir, [string]$Destination) {
    New-Item -ItemType Directory -Force -Path $Destination | Out-Null
    $models = Get-ChildItem $PackDir -Recurse -File | Where-Object {
        $_.Extension -in @(".glb", ".gltf", ".fbx")
    }
    if (!$models) { throw "No 3D models found in $PackDir" }

    foreach ($model in $models) {
        $safe = $model.Name
        $target = Join-Path $Destination $safe
        if (Test-Path $target) {
            $safe = "$($model.BaseName)-$([Math]::Abs($model.FullName.GetHashCode())).$($model.Extension.TrimStart('.'))"
            $target = Join-Path $Destination $safe
        }
        Copy-Item $model.FullName $target -Force
    }

    Get-ChildItem $PackDir -Recurse -File | Where-Object {
        $_.Extension -in @(".png", ".jpg", ".jpeg", ".webp")
    } | ForEach-Object {
        $texDir = Join-Path $Destination "Textures"
        New-Item -ItemType Directory -Force -Path $texDir | Out-Null
        Copy-Item $_.FullName (Join-Path $texDir $_.Name) -Force
    }
}

function Copy-AudioPack([string]$PackDir, [string]$Destination) {
    New-Item -ItemType Directory -Force -Path $Destination | Out-Null
    $files = Get-ChildItem $PackDir -Recurse -File | Where-Object {
        $_.Extension -in @(".ogg", ".wav", ".mp3")
    }
    if (!$files) { throw "No audio files found in $PackDir" }
    foreach ($file in $files) {
        Copy-Item $file.FullName (Join-Path $Destination $file.Name) -Force
    }
}

$packs = @(
    @{
        Name = "city-commercial"
        Url = "https://opengameart.org/sites/default/files/kenney_city-kit-commercial_2.1.zip"
        Destination = (Join-Path $kenneyRoot "city\commercial")
    },
    @{
        Name = "city-industrial"
        Url = "https://opengameart.org/sites/default/files/kenney_city-kit-industrial_2.0.zip"
        Destination = (Join-Path $kenneyRoot "city\industrial")
    },
    @{
        Name = "city-suburban"
        Url = "https://opengameart.org/sites/default/files/kenney_city-kit-suburban_2.0.zip"
        Destination = (Join-Path $kenneyRoot "city\suburban")
    },
    @{
        Name = "city-roads"
        Url = "https://opengameart.org/sites/default/files/kenney_city-kit-roads.zip"
        Destination = (Join-Path $kenneyRoot "city\roads")
    },
    @{
        Name = "car-kit"
        Url = "https://opengameart.org/sites/default/files/kenney_car-kit_3.1.zip"
        Destination = (Join-Path $kenneyRoot "vehicles")
    },
    @{
        Name = "mini-characters"
        Url = "https://opengameart.org/sites/default/files/kenney_mini-characters.zip"
        Destination = (Join-Path $kenneyRoot "characters")
    }
)

foreach ($pack in $packs) {
    $dir = Expand-Pack $pack.Url $pack.Name
    Copy-AllModels $dir $pack.Destination
}

$uiDir = Expand-Pack "https://opengameart.org/sites/default/files/kenney_interfaceSounds.zip" "ui-audio"
Copy-AudioPack $uiDir (Join-Path $audioRoot "ui")

$rainDir = Expand-Pack "https://opengameart.org/sites/default/files/Rain%20OGG.zip" "rain"
$rainFiles = Get-ChildItem $rainDir -Recurse -File -Filter "*.ogg" | Sort-Object Name
if (!$rainFiles) { throw "No OGG rain loops found" }
New-Item -ItemType Directory -Force -Path (Join-Path $audioRoot "weather") | Out-Null
Copy-Item $rainFiles[0].FullName (Join-Path $audioRoot "weather\rain.ogg") -Force
if ($rainFiles.Count -gt 1) {
    Copy-Item $rainFiles[1].FullName (Join-Path $audioRoot "weather\rain-heavy.ogg") -Force
}

Download-File "https://opengameart.org/sites/default/files/crowd_shouting_0.ogg" (Join-Path $audioRoot "city-crowd.ogg")

$license = @"
METRÓPOLE ∞ — Third-party asset notice
Generated by tools/fetch-third-party-assets.ps1

Kenney City Kit (Commercial) 2.1 — CC0 1.0
Source: https://opengameart.org/content/city-kit-commercial
Kenney City Kit (Industrial) 2.0 — CC0 1.0
Source: https://opengameart.org/content/city-kit-industrial
Kenney City Kit (Suburban) 2.0 — CC0 1.0
Source: https://opengameart.org/content/city-kit-suburban
Kenney City Kit (Roads) — CC0 1.0
Source: https://opengameart.org/content/city-kit-roads
Kenney Car Kit 3.1 — CC0 1.0
Source: https://opengameart.org/content/car-kit
Kenney Mini Character 1 / Mini Characters — CC0 1.0
Source: https://opengameart.org/node/165679
Kenney Interface Sounds — CC0 1.0
Source: https://opengameart.org/content/interface-sounds
Rain (loopable), Ylmir — CC0
Source: https://opengameart.org/content/rain-loopable
Crowd Shouting/Speaking Ambience, StarNinjas — CC0
Source: https://opengameart.org/content/crowd-shoutingspeaking-ambience

CC0: https://creativecommons.org/publicdomain/zero/1.0/

Attribution is not required by CC0, but source/author information is retained here for provenance.
"@

Set-Content -Path (Join-Path $assetRoot "THIRD_PARTY_ASSETS.txt") -Value $license -Encoding UTF8

$manifestFiles = Get-ChildItem $assetRoot -Recurse -File | Where-Object {
    $_.Extension -in @(".glb", ".gltf", ".fbx", ".ogg", ".wav", ".mp3")
} | ForEach-Object {
    $relative = $_.FullName.Substring($ProjectRoot.Length).TrimStart('\','/').Replace('\','/')
    "res://$relative"
} | Sort-Object -Unique
Set-Content -Path (Join-Path $assetRoot "asset_manifest.txt") -Value $manifestFiles -Encoding UTF8

$modelCount = (Get-ChildItem $kenneyRoot -Recurse -File | Where-Object { $_.Extension -in @(".glb",".gltf",".fbx") }).Count
$audioCount = (Get-ChildItem $audioRoot -Recurse -File | Where-Object { $_.Extension -in @(".ogg",".wav",".mp3") }).Count
$characterCount = (Get-ChildItem (Join-Path $kenneyRoot "characters") -Recurse -File | Where-Object { $_.Extension -in @(".glb",".gltf",".fbx") }).Count

Write-Output "METROPOLE_ASSET_FETCH_OK models=$modelCount characters=$characterCount audio=$audioCount"

if ($modelCount -lt 80) { throw "Expected at least 80 3D models, got $modelCount" }
if ($characterCount -lt 4) { throw "Expected at least 4 character models, got $characterCount" }
if ($audioCount -lt 20) { throw "Expected at least 20 audio files, got $audioCount" }

Remove-Item $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
